---
- name: Base playbook for PoC
  hosts: localhost
  gather_facts: true

  tasks:
    - shell: "echo 'Begin once off setup for {{account}} {{region}}'"
      register: account_region_setup

    - debug:
        var: account_region_setup
