---
- name: Base playbook for PoC
  hosts: localhost
  gather_facts: true

  tasks:
    - shell: "echo 'Begin once off setup for {{account}} {{region}}'"
      register: account_region_setup

    - debug:
        var: account_region_setup
---
- hosts: all
  become: true
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: # a bucket is required
    ansible_aws_ssm_region: us-east-1

  tasks:
    - name: Wait for SSM Connection from Host
      ansible.builtin.wait_for_connection:

      #https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_metadata_facts_module.html
    - name: Gather Instance Metadata
      amazon.aws.ec2_metadata_facts:

    - name: Print EC2 instance information
      debug:
        msg: >
          Account ID: {{ ansible_ec2_instance_identity_document_accountid }}
          Instance ID: {{ ansible_ec2_instance_id }}
          Instance Type: {{ ansible_ec2_instance_type }}
          Private IP: {{ ansible_ec2_private_ip }}
          Public IP: {{ ansible_ec2_public_ip }}
          Region: {{ ansible_ec2_placement_region }}
          Availability Zone: {{ ansible_ec2_placement_availability_zone }}