name: "2: Ansible List all Discovered Instances"
run-name: "Ansible List Discoverd Instances by ${{ github.actor }}"

on:
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    name: "${{ matrix.account_id }}: ${{matrix.region}}"
    strategy:
      fail-fast: false
      matrix:
        account_id: [MY_ACCOUNT_ID1, MY_ACCOUNT_ID2]
        region: [us-east-1, eu-west-1]
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: echo "Running on ${{ matrix.account_id }} ${{matrix.region}}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ matrix.account_id }}:role/$OIDC_ROLE_NAME
          aws-region: ${{matrix.region}}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10.12'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt

      - name: Show Ansible Inventory
        run: |
          ansible-inventory -i ansible/inventory/${{matrix.region}}.aws_ec2.yml --list --export --output "${{ matrix.account_id }}-${{matrix.region}}"
          jq .aws_ec2.hosts "${{ matrix.account_id }}-${{matrix.region}}" >> $GITHUB_STEP_SUMMARY
