name: "1: Ansible Playbook"
run-name: "Ansible Playbook run by ${{ github.actor }}"

on:
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    name: "${{ matrix.account_id }} - ${{matrix.region}}"
    strategy:
      matrix:
        account_id: [MY_ACCOUNT_ID1, MY_ACCOUNT_ID2]
        region: [us-east-1, eu-west-1]
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: echo "Running on ${{ matrix.account_id }} ${{matrix.region}}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ matrix.account_id }}:role/$OIDC_ROLE_NAME
          aws-region: ${{matrix.region}}

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook ansible/playbook.yml --extra-vars "account=${{ matrix.account_id }}" --extra-vars "region=${{matrix.region}}"